### ISSUE TITLE
update docs for using w/ stack and cabal sandboxes

### ISSUE THREAD

**Issue by noughtmare** [yi-editor/yi-editor.github.com#8]
>The recipe for installing yi using a cabal sandbox (link) says to use:

>`$ cabal exec ./dist/build/yi/yi`

>to start yi. However, I think the correct command (tested with cabal-1.22.8.0) is simply:

>`$ cabal exec yi`

>Also, for the stack recipe, it should mention that the way to invoke yi is:

>`$ stack exec yi`

Also

>Its actually `stack exec yi --package yi`

see [yi-editor/yi#869](https://github.com/yi-editor/yi/issues/869)

**Comment by siddhanathan** [comment]
Thanks for mentioning it here :)
